"""migration 5

Revision ID: 2f659e16f7d3
Revises: b64febd39d11
Create Date: 2023-03-11 13:23:32.482470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f659e16f7d3'
down_revision = 'b64febd39d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sum', sa.Numeric(precision=12, scale=2), nullable=True))

    with op.batch_alter_table('types_of_moves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('types_of_moves', schema=None) as batch_op:
        batch_op.drop_column('debit')

    with op.batch_alter_table('cash_receipts', schema=None) as batch_op:
        batch_op.drop_column('sum')

    # ### end Alembic commands ###
