"""migration 17

Revision ID: 845e44ce95cc
Revises: 2712e7f0800c
Create Date: 2023-03-18 20:09:39.796382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '845e44ce95cc'
down_revision = '2712e7f0800c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('types_of_moves', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('types_of_moves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', mysql.VARCHAR(collation='utf8mb4_0900_as_ci', length=100), nullable=False))

    # ### end Alembic commands ###
