"""migration 6

Revision ID: a1a9fe195248
Revises: 2f659e16f7d3
Create Date: 2023-03-11 13:25:47.736104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1a9fe195248'
down_revision = '2f659e16f7d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_receipts', schema=None) as batch_op:
        batch_op.alter_column('sum',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False)

    with op.batch_alter_table('types_of_moves', schema=None) as batch_op:
        batch_op.alter_column('debit',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('types_of_moves', schema=None) as batch_op:
        batch_op.alter_column('debit',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('cash_receipts', schema=None) as batch_op:
        batch_op.alter_column('sum',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True)

    # ### end Alembic commands ###
