"""migration 13

Revision ID: aaf9df49f48d
Revises: d2bfea76dfaf
Create Date: 2023-03-16 18:36:26.522738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf9df49f48d'
down_revision = 'd2bfea76dfaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('cash_desk_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('sum', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['cash_desk_id'], ['cash_desks.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['currency_code'], ['currency.code'], ),
    sa.ForeignKeyConstraint(['type_id'], ['types_of_moves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cash_expenses')
    # ### end Alembic commands ###
