"""migration 8

Revision ID: cf88bd6b4c93
Revises: 54a34ad9fb51
Create Date: 2023-03-12 10:38:17.336315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf88bd6b4c93'
down_revision = '54a34ad9fb51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_code', sa.String(length=3), nullable=False))
        batch_op.create_foreign_key(None, 'currency', ['currency_code'], ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_receipts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('currency_code')

    # ### end Alembic commands ###
