"""migration 12

Revision ID: d2bfea76dfaf
Revises: 7b669cb2a468
Create Date: 2023-03-13 17:35:46.386654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2bfea76dfaf'
down_revision = '7b669cb2a468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', mysql.VARCHAR(collation='utf8mb4_0900_as_ci', length=200), nullable=False))

    # ### end Alembic commands ###
